### ISSUE TITLE
configurable numeraire token

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1063]
> i think the wallet should have a setting for the numeraire token and it should be usdc by default

https://discord.com/channels/824484045370818580/1044457038886998137/1237431382930886696

**Comment by hdevalence** [comment]
Currently there’s already code that saves prices, and that code has to have a choice of numeraire, at some point that should be a config setting (even if there is no UI for it) and then later we can add UI

**Comment by Valentine1898** [comment]
In order to be able to switch `numeraire ` on the fly, we need to save prices for all possible `numeraires` 

Note that the list of possible numeraires accessed in the registry 
https://github.com/prax-wallet/registry/blob/d2b78bd4c87c79829c5fd527e901bae31344a53a/registry/penumbra-testnet-deimos-7.json#L376-L379

Also, the point is that the API allows you to return a list of `equivalent_values`, which is what we are doing now, effectively returning a list of prices for each asset across all `numeraires`

Are we sure that the numeraire setting should be in wallet and not in dApp (minifront)?

**Comment by hdevalence** [comment]
What if we just expired the old prices?

**Comment by Valentine1898** [comment]
> What if we just expired the old prices?

We have `PRICE_RELEVANCE_THRESHOLDS` which determines how many blocks the price stays current. Prices older than THRESHOLD will not be returned. 
https://github.com/penumbra-zone/web/blob/336455b1efcf4aef1747c1223e1e35ffa6785067/packages/constants/src/assets.ts#L1-L6

**Comment by Valentine1898** [comment]
If you mean undo delete old prices when changing `numeraire` in settings, then it is possible in general, but still the user will have to wait until we scan some number of new blocks and get prices from them by new `numeraire`

**Comment by hdevalence** [comment]
Yeah, I think that would be fine, whenever we get around to implementing this, I don't think it's high priority
