### ISSUE TITLE
Candlestick chart on estimate

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1183]
With https://github.com/penumbra-zone/penumbra/pull/4398, we now have a [Candlestick data](https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.core.component.dex.v1#penumbra.core.component.dex.v1.CandlestickData) that can be requested from the frontend.

This will be helpful in augmenting our swap & auction estimate component. After an estimate request is made, we should make a `CandlestickDataRequest`, transform the data as needed for our charting library, and add to the estimate view:

<img width="912" alt="Screenshot 2024-05-28 at 12 47 32 PM" src="https://github.com/penumbra-zone/web/assets/16624263/ff854a1d-d90c-4067-a6db-652c214ad160">

Libraries to consider

- visx has boxplot support: https://airbnb.io/visx/docs/stats
- chartjs has support: https://www.chartjs.org/chartjs-chart-financial/
- others? d3js?

**Comment by grod220** [comment]
@turbocrime can you update the status on this?

**Comment by turbocrime** [comment]
candlestick chart did merge in #1220, but is issued as broken by https://github.com/penumbra-zone/web/issues/1347. i started work on that but was instructed to focus on page api and react wrapper packages which have been through several refactor/wait/review iterations since then, with all available other attention taken by other high priority things

and then all the testnet infra was taken down, and the `penumbra-1` chain afaict has no swap activity to examine charts for. this is essentially impossible to work on without a chain containing swap data.

i rebased and spent some time with a local dev net today, i'll open a PR with my rebased work.
