### ISSUE TITLE
Sub-auction maximum outputs are too large

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1224]
With some input assets and a short enough auction time, tendermint sometimes rejects auctions with the complaint that the maximum output amount is 'more than 53 bits wide' which corresponds to a mask of `0x003FFFFFFFFFFFFF`

If the sub-auctions are exceeding the maximum output size of an auction, there are not enough sub-auctions.

**Comment by jessepinho** [comment]
cc @erwanor 

At the moment, we're copying pcli's implementation for generating auctions. @erwanor, have you seen this error in pcli as well? Just want to make sure it's not a web-specific bug. Maybe the logic should take the max/min outputs into account when deciding how many sub-auctions to create?

**Comment by erwanor** [comment]
Related to #1124, this isn’t caused by the web extension, it’s a hard limit on how much input we allow per auction. The node software doesn’t expect values that are beyond 2^52 - 1. 

This should only happen when using an asset with an extreme base denom like test_usd. So beyond handling the error elegantly, there aren’t action items to implement.
