### ISSUE TITLE
Asset filter box errors 🐛 

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#1328]
This looks related to the presence of unknown assets in the users balance

https://github.com/penumbra-zone/web/assets/16624263/4647466d-9a48-44f8-b37f-d16e3261e0d0

**Comment by TalDerei** [comment]
related to https://github.com/penumbra-zone/web/issues/1289?

**Comment by Valentine1898** [comment]
The `AssetSelector` search does not actually take into account that the user may have unknown assets. 

This is only reproduced for Send, because for Swap and Ibc we filter out unknown assets. 

The search is based on `display` or `symbol` fields, and unknown assets do not have these fields. 

Possible solutions:
1. Filter out unknown assets for Send actions as well
2. Simply ignore unknown assets in the search 
3. Make the search more flexible, and make it possible to search both among known assets (by display and symbol fields) and unknown assets by `bech32mAssetId`.

**Comment by Valentine1898** [comment]
I would favor 

> Simply ignore unknown assets in the search
