### ISSUE TITLE
Npm package publishing

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#138]
We need a strategy/method on how we publish our `@penumbra-zone/<package>` 's. How often should we do this? Is there a way CI/CD can automatically detect diffs of packages and publish the new version?

**Comment by TalDerei** [comment]
Referenced in #218. The NPM publishing workflow exists in a state where the web app and extension are synchronized, and the dialogue between them hasn't been the source of breaking changes. The combination of protobuf spec changes and new testnet deployments, without publishing an updated extension, was the major source of breakage. Finalizing the protobuf spec https://github.com/penumbra-zone/penumbra/issues/3720 helps, but there are still pain points related to web-related breaking changes if there's a mismatch between web app and state of the extension. 

One track we've discussed is a multi-branch workflow where 

@grod220 cc

**Comment by TalDerei** [comment]
Referenced in https://github.com/penumbra-zone/web/issues/218. The NPM publishing workflow exists in a state where the web app and extension are synchronized, and the dialogue between them hasn't been the source of breaking changes. The combination of protobuf spec changes and new testnet deployments, without publishing an updated extension, was the major source of breakage. Finalizing the protobuf spec https://github.com/penumbra-zone/penumbra/issues/3720 helps, but there are still pain points related to web-related breaking changes if there's a mismatch between web app and state of the extension.

One track we've discussed is a multi-branch workflow where we have a development branch that we merge things into instead of main acting as the deployment branch. The main branch would act as what's in production, and the dev branch would be what's in preview. This would increase the complexity of the workflow, but it's one method to reduce the number of breaking changes. @conorsch iirc, you already do this implicitly when we release a point release in the monorepo. 

Another track would be an additional manual github action, where the GitHub action would be a production web app deployment. We’d have the existing continuous deployments going to a preview, and the secondary one would be a manual action whenever we publish or there's an extension update. This has also been recently discussed as a viable option. 

@grod220 cc

**Comment by grod220** [comment]
At the moment, given things are in flux, we are simply deploying the web app + extension manually via github actions. However, maybe after a month or two, we should return to continuous deployment of the web app (assuming the messaging api is stable).

This issue really had in mind third-party wallets (keplr, leap) that we eventually will want to expose all of our work. We want them (with fairly little effort) to be able to import and use these packages to enable using Penumbra for their users. However, at the moment, we aren't publishing them to npm.

**Comment by grod220** [comment]
This tracking issue https://github.com/penumbra-zone/web/issues/729, with the broken down tasks, should be the new thing to track
