### ISSUE TITLE
claim swaps with locked wallet

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1439]
It appears that currently, swaps can be claimed even when the wallet is locked. We should not be able to perform any actions with a locked wallet. Instead, the "not logged in" toast should be displayed.

**Comment by VanishMax** [comment]
@TalDerei @grod220 It seems that we can know about the not-logged-in state only when approving transactions. Claiming the unclaimed swaps doesn't trigger the approval because it was approved previously. We also can't use the `client` library since the 'logged in' state is not defined there and probably shouldn't be defined as the logic is wallet-specific.

I guess the issue here is bigger – we need to think of what the locked state is. Does 'locked' mean 'disconnected' in this case? It would make sense it terms of prohibiting the actions but also won't show the UI.

**Comment by grod220** [comment]
Interesting case. Claiming a swap feels like a low-risk action given the prior approval. @TalDerei what do you think? Can close?

**Comment by TalDerei** [comment]
> Interesting case. Claiming a swap feels like a low-risk action given the prior approval. @TalDerei what do you think? Can close?

can we hold off on closing until I get a chance to investigate today?

**Comment by TalDerei** [comment]
this fell through the cracks due to higher priority work – diving into it, there doesn't seem to be a straightforward way to resolve this. Considering the prior transaction approval and the fact that we already perform other background operations on a locked extension, I agree that this is generally a low-risk action. closing unless there's dissenting opinions
