### ISSUE TITLE
clearing extension cache isn't working properly

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1496]
refreshing the extension cache on the mainnet displays irregular behaviors, possibly leading to unpredictable cache states and causing synchronization issues. Refreshing the cache should immediately start resyncing rather than throwing an error and navigating back to the onboarding page. 

cc @turbocrime 

https://github.com/user-attachments/assets/26fb65c0-a35f-4451-bd34-597241aee151

**Comment by turbocrime** [comment]
currently, there is no good way to ensure that the block processor and wallet services are killed and cleaned up properly, so the extension restarts its background worker. this guarantees that no old state remains.

restarting the background worker breaks the page context.

the immediate next thing that happens is the background worker begins genesis sync again, which due to single-threadedness blocks the listeners that would normally init the new content scripts, and the rpc services that would serve requests.

a few things need to happen to make this nicer

1. abort controllers for all wallet services
2. content scripts that handle loss of context
3. better abort signalling for content scripts https://github.com/penumbra-zone/web/pull/1517

and ideally,

3. independent worker for rpc services
4. independent worker for block processor

**Comment by TalDerei** [comment]
closing in favor of https://github.com/penumbra-zone/web/issues/1496 

this issue provides additional relevant context to be aware of
