### ISSUE TITLE
Planner should support lack of a source account

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#1535]
Specifically for delegator voting, it's important to be able to construct transactions that do not have a restricted source.

The RPC documentation also indicates that omitting a source is valid in order to indicate this preference.

#1499 recently prevented an absent source https://github.com/penumbra-zone/web/commit/35ed14caad4c13767d1238efbb3b324a3df061a3

what was the specific motivation for issue #1433 requesting this? it seems to refer to #1412 (edit: perhaps #1421) however the only mention of source in that PR is where it looks for native tokens to pay gas

it does not seem strictly necessary to require source for that. if source is absent, it should be permissible to pay gas from any account, right? so the requirement could be reversed

**Comment by Valentine1898** [comment]
Delegate voting is directly related to staking and delegating. 
The design of staking in minifront assumes that user accounts are isolated, and that they can manage their stakes on each account separately. However, the user cannot delegate from all accounts with a single transaction.
It seems to me that it would be a good idea to port this design for delegate voting as well. I.e. I think that instead of voting with all accounts in one transaction there should be an interface where the user can switch between accounts and vote for each account separately.

**Comment by TalDerei** [comment]
if we remove the strict enforcement of the source in the TPR and planner, you would be able to spend funds from any account, in theory. Currently, we have account isolation and limit the ability to spend funds from different accounts. I however agree with @Valentine1898's idea here.
