### ISSUE TITLE
block scanning should use block acceleration features of the TCT

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1576]
clients stream compact blocks and construct a filtered instance of the SCT. Currently, we're trial-decrypting every encrypted payload for every block retrieved from the full node. However, our wasm view server implementation doesn't yet take advantage of the TCT acceleration features detailed in [Penumbra issue #842](https://github.com/penumbra-zone/penumbra/issues/842). In that context, we can use the fact that penumbra commits the intermediate root hash of every block, and client synchronization can stream the root hashes of each block _without_ needing to know the individual commitments. This approach would reduce the number of Merkle hashing operations needed to insert a block into the SCT.

our [scan_block](https://github.com/penumbra-zone/web/blob/main/packages/wasm/crate/src/view_server.rs#L116) implementation was built using `mock_client` as a template. Instead, we should employ the TCT's API, specifically the [insert_block](https://github.com/penumbra-zone/penumbra/blob/main/crates/crypto/tct/src/epoch.rs#L202) and [insert_epoch](https://github.com/penumbra-zone/penumbra/blob/main/crates/crypto/tct/src/tree.rs#L556) methods, to accelerate block syncing.

we've essentially built this highly optimized merkle tree (**Tierd Commitment Tree**) designed for efficient client sync, but we're not taking advantage of it's fundamental properties.

**Comment by hdevalence** [comment]
the relevant code in the rust view server is here: https://github.com/penumbra-zone/penumbra/blob/main/crates/view/src/sync.rs#L111-L117

the optimization is: if the result of scanning the block is that there were no decryptions, use `insert_block`.

there's no need to use the epoch-level insertion features at this time as that is more complicated to employ (scanning goes block by block).

**Comment by hdevalence** [comment]
this optimization isn't completely trivial to port to the wasm view server, because it inlines together the trial decryption and the SCT insertions into one sequence of operations:

https://github.com/penumbra-zone/web/blob/main/packages/wasm/crate/src/view_server.rs#L123-L130

instead, these operations can be cleanly separated by using in-memory advice, as in the native code: https://github.com/penumbra-zone/penumbra/blob/main/crates/view/src/sync.rs#L86-L109 : first, build a lookup table of successful decryptions (the "advice"), then use it when processing each note payload. that way, it's easy to write code that skips over an empty block, as all the trial decryption is done up-front.

**Comment by hdevalence** [comment]
Added some code that ports the native rust code's advice mechanism to the wasm crate in #1716 but it needs testing to check that it doesn't mess up the SCT synchronization
