### ISSUE TITLE
Memo handling is incorrect

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#160]
Steps to reproduce:

1. Using `pcli` (perhaps with a different wallet), generate an address.
2. Use the web extension's "send" dialog to send to that address. Add a memo text and click "Hide Sender from Recipient".
3. Use `pcli v tx HASH` to view the transaction.
4. See that the memo text is discarded rather than included in the transaction.
5. Use `pcli tx send 1penumbra --to RETURN_ADDRESS` to see that the address specified as the return address is invalid.

**Comment by turbocrime** [comment]
<img width="804" alt="Screen Shot 2023-10-31 at 13 32 14" src="https://github.com/penumbra-zone/web/assets/134443988/9f07e5ec-8110-4804-90c5-74ee4c6e2365">

successfully plumbed a memo, and , but the real issue is the problems i discovered along the way.

i have several questions. writing up notes in a PR this afternoon

**Comment by turbocrime** [comment]
#180 was obsoleted and work needs to restart on this
