### ISSUE TITLE
possible unknown assets bug

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#1784]
when spinning up my local pd instance and cometbft, I encounter unknown assets because the symbol in the [metadata](https://github.com/penumbra-zone/web/blob/main/packages/ui/components/ui/value/index.tsx#L30) is missing. I'm unsure whether this is happening only to me or if it's a registry-related issue?

<img width="1840" alt="Screenshot 2024-09-14 at 2 34 42 PM" src="https://github.com/user-attachments/assets/44038bc0-3a4d-4edf-aa5b-9172ca641a3c">

<img width="1840" alt="Screenshot 2024-09-14 at 2 34 39 PM" src="https://github.com/user-attachments/assets/9c3150b0-0043-4ad0-9ed6-e3300313a00f">

**Comment by grod220** [comment]
Any chance the local pd node used to have the chain id of `penumbra-testnet-deimos-8-x6de97e39`? In short, the assets are unknown because:
- There is not a [registry json](https://github.com/prax-wallet/registry/tree/main/registry/chains) called `penumbra-testnet-phobos-x6b520739`
- Given this is a testnet chain id, it will check for a registry called `penumbra-testnet-phobos`. It does not find that either.

@conorsch, any chance we could we change the local pd chain id to `penumbra-testnet-phobos-1-x6de97e39`? This will ensure it will hit the registry file there.

**Comment by TalDerei** [comment]
> Any chance the local pd node used to have the chain id of `penumbra-testnet-deimos-8-x6de97e39`?

When I tried modifying the chain id to `penumbra-testnet-deimos-8-x6de97e39`, I still encountered the same problem?

<img width="1728" alt="Screenshot 2024-09-16 at 7 37 25 AM" src="https://github.com/user-attachments/assets/a7b8414a-a463-4719-b464-cf21aa48b9e6">

**Comment by TalDerei** [comment]
forgot to mention that the issue was related to https://github.com/prax-wallet/registry/pull/89. It was failing to fetch from the registry because it was trying to find penumbra-testnet-deimos-8.json rather than penumbra-testnet-deimos-8-x6de97e39.json. Bumping the registry in https://github.com/prax-wallet/prax/pull/197  resolves this.
