### ISSUE TITLE
Wasm errors not bubbling up

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#232]
Try sending a transaction to: penumbra1rtjzkgm553lyqufnr4sp368dp8rajlm2p96hmclld3r4wcqapezraav04xq5849ksq7qf8jvhv37y4uqxsjv4s684au3vc2g203f8um2f0rwsgm8qjf7anvqgrgdf0safyxsr9

The extension console will have the true error. The error toast does not.

**Comment by Valentine1898** [comment]
The issue is that instead of error we get a panic on the rust side. In all other cases, when entering a non-existent address, we display in toast the error received from rust 
<img width="1440" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/ea8ec394-7557-4997-935f-543738222e6c">
We can't catch panics on the rust side of wasm [link](https://users.rust-lang.org/t/catch-panic-in-wasm/57569)
On the TS side, we catch the panic but will not be able to get its details and error msg

At the same time, it seems like the right solution is to fix the Rust code that creates a panic instead of returning an error, I'll start a corresponding issue in the penumbra repo. 

Interesting fact, I broke faucet in discord when I typed this address into it

**Comment by grod220** [comment]
Ah, yes indeed. We should fix that panic. Opened a PR.

**Comment by Valentine1898** [comment]
There doesn't seem to be a quick fix for https://github.com/penumbra-zone/penumbra/issues/3332 , so I'll move this to status blocked

**Comment by grod220** [comment]
Actually, for the web side of things, it's simply a learning that Rust panics cause unexpected behavior for the web. Think we can close this and just stay on top of the issue in the other repo.
