### ISSUE TITLE
transport refactor and service routing

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#240]
## goals and motivation

bufbuild and connectrpc tooling are very extensible. they provide many features that should be exploited to reduce the size of the codebase, such as service routing, implementation typing, and message type recovery.

features they do not provide could be added in such a way that developer experience of the tooling remains close to standard convention, as demonstrated previously with the demo transport implementation.

developer experience is critical to community adoption and a good developer experience directly translates to higher quality community apps. the implementation should be conceptually simple and enforce correctness.

simplifying and improving the transport and routing, and enforcing implementation correctness with types derived from protobuf spec, will accelerate development, testing, and any service spec revisions.

## transport client

the untrusted client is responsible for constructing a local routerTransport which should be provided as a published npm package. this transport should

* be type agnostic
* support all service methods
* bind to one specified service
* initiate a private connection
* send rpc requests
* match responses to requests
* correctly recover response types
* enforce local timeouts
* provide request abortion

one major shortcoming of the existing event transport client is that all messages are emitted and received on the window document. message channels are available in the standard browser API and should be used for all communication.

## backend reception and routing

currently, the backend transport receiver attempts no identification or authorization of the client origin. this should occur before messages are accepted or acknowledged.

interactive authentication must be resolved at this location.

the receiver might be implemented by a service platform plug-in for the connectrpc tooling. this would enable use of the service-side routing stubs from the buf registry, which provide type recovery, context handling, and routing to implemented services.

## content script page-extension shim

this is the boundary at which messages must transition from the browser messaging API to Chrome's custom extension messaging API. if we avoid simply emitting all messages globally, connection management of some type must happen at this location.

content scripts are ultimately untrusted, so no validation or authentication should occur here.

**Comment by turbocrime** [comment]
so far, i have major work towards connection management and a simplified client.

restricting messages to private channels should massively reduce the number of events emitted on the page and on all extension documents.

will see if i can clean it up and publish a branch so work is visible

**Comment by hdevalence** [comment]
> interactive authentication must be resolved at this location.

I don't think we want to have any interactive authentication -- I think the only authentication we want to have at the transport level would be (1) non-interactive (2) origin-scoped (3) very granular:

1. We don't want to have interactive auth at the transport layer, it doesn't make sense to have users interact with every request. The transport layer's notion of auth can only encompass the capability to _make_ a request, it can't get into request contents. We may want to have user interaction while _processing_ a request (e.g., the custody service's `AuthorizeRequest` should present a plan for approval) but this is an application-level concern of the server handler, rather than the transport.
2. We don't have much more information to go on than the origin, but this is probably enough for our use case.
3. I don't think we need to express a more granular notion of capability than a boolean "connected or not".

So, I think the only kind of auth we'll want to have eventually is just a simple "is this origin allowed to make requests to the extension". For now we don't even need to have that scope, either.

**Comment by hdevalence** [comment]
It would be ideal if we could reuse both the client stubs and the server stubs from Connect, and just have a custom transport in the middle, so that:

- on the web page (client) side, making requests looks just like making requests to a remote endpoint, using the generated client stubs;
- on the extension (server) side, we can write server implementations for arbitrary services using the generated server stubs, and then plug them into an existing router, rather than having to reimplement routing logic.

**Comment by turbocrime** [comment]
>I don't think we want to have any interactive authentication -- I think the only authentication we want to have at the transport level would be (1) non-interactive (2) origin-scoped (3) very granular

i had notes which outlined a few different kinds of auth i might expect to need and that specific nomenclature was referring to that document. up now at #242

all types of auth are not necessarily something that should be interactive every time, but it would be nice to support things like "wait for this popup to resolve, then maybe continue" as #186 seemed to ask for. these could be implemented in-handler or if the bufbuild plugin is very successful, as request context, as an interceptor, or in other service-side auth tooling

**Comment by turbocrime** [comment]
>It would be ideal if we could reuse both the client stubs and the server stubs from Connect, and just have a custom transport in the middle,

that is a primary goal of this work

**Comment by turbocrime** [comment]
much progress in #255

**Comment by turbocrime** [comment]
#255 merged

some progress on routing refactor is already made and i'll work on making that visible

simplest way to implement approvals in the handlers should be via the context parameter but that still needs some conceptual work

i think i'll also try to revive the UI work of #126 and #73 to provide the origin authentication that connection manager expects

**Comment by turbocrime** [comment]
translated the "handlers" in the existing "router" directly into `MethodImpl`s fairly successfully. the adapter is not what it should be (wrapped promise client instead of wrapped universalhandler) but improving that soon. proxying should be as easy as constructing a client to a remote.
