### ISSUE TITLE
User should be able to choose the account from which he is going to spend funds when sending (UI issue)

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#244]
Part of https://github.com/penumbra-zone/web/issues/161

It actually seems to be a challenging UI task 

Selecting an account also affects the display of Select asset popup, because now we display the total balance from all accounts there. 
<img width="409" alt="image" src="https://github.com/penumbra-zone/web/assets/25391690/f70e934c-283a-49fb-b278-1d0df3a57dae">

Should account selection be optional? If the user has not selected anything, we can spend notes from all accounts and display the total balance as it is now (planner request handler and wasm supports this).

**Comment by grod220** [comment]
Ah, indeed it is a bit tricky. I think we had an initial idea of account selector at the top, which would make the assets picker responsive.

However, this is not the best UX, because we don't really know which accounts have assets. We probably should simply change the select asset modal (image above) and list assets by account number. So something like:

| Account |   Asset   | Amount |
|---------|-----------|--------|
|   0     | penumbra  | 123123 |
|   1     | gm        |   99   |
|   1     | penumbra  |  882   |
|  912    | usdc      |   12   |

Accounts are such a fundamental aspect of Penumbra. I lean toward requiring users to select by account and not have the auto-selecting behavior.

**Comment by Vadim121197** [comment]
@grod220 I have a suggestion to change the zustand logic! now we have a problem that when going to the Send page we are adjusting the balances in the react-router-dom loader, but it would be cool to set the values for asset and account in the loader as well! for the asset we use a predefined value from an array, but the user may not have this asset! here is an example of what I propose - https://codesandbox.io/p/sandbox/react-router-dom-loaders-layout-createbrowserrouter-zustand-grq7zz?file=%2Fsrc%2FApp.tsx%3A14%2C10-14%2C15. For now, we can't use the existing zustand logic because useStore is a hook, and a hook can't be used in loader

**Comment by Vadim121197** [comment]
![Image](https://github.com/penumbra-zone/web/assets/52686175/837a1c9b-be4f-4278-ae6c-36a6ca6bb476)

@grod220

**Comment by grod220** [comment]
> we use a predefined value from an array

In the loader, we call `getBalancesByAccountIndex()`. That should return everything we need to display this UI. We shouldn't use a predefined array of denoms and fetch according to that. I don't think we are doing that though 🤔 

> I have a suggestion to change the zustand logic

I'm not sure any zustand changes are necessary for this feature. It looks like that UI screenshot is the fulfillment of this task.
