### ISSUE TITLE
eliminate openly accessible endpoints

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#256]
the goal of the wallet extension is to provide wallet services to third-party pages. however, it is not necessary for the wallet to provide analyzable surfaces to all third-party pages.

currently, the extension attempts no authentication of origins, and all attempted connections receive service. the extension should not acknowledge unpermissioned origins in any way, not even an explicit refusal.

currently, the extension provides conveniences for detection and status indication to the webapp. the extension should not manifest any web-accessible resources, or any detection or status endpoints.

inferring presence, readiness, and status is the responsibility of the webapp. presence and readiness are easily evidenced by acknowledgement of a specced RPC request. any status that matters will likewise be present in the result of an appropriate RPC request.

**Comment by turbocrime** [comment]
https://github.com/penumbra-zone/web/blame/48985141b30da200c4c96a6a67139e9da9029839/apps/extension/public/manifest.json#L22-L27

https://github.com/penumbra-zone/web/blob/48985141b30da200c4c96a6a67139e9da9029839/apps/webapp/src/fetchers/is-connected.ts

**Comment by turbocrime** [comment]
#73 "connected sites" list provides origin authentication

**Comment by turbocrime** [comment]
Web apps may assume the extension is not connected, until an attempted request is acknowledged by the extension with a response.

Web apps should not be concerned with their own authorization, the extension manages authorization.

A web app should by default display instructions directing the user to install the extension and provide it permission. When it receives responses from the extension, it may reliably infer it is connected, and operate accordingly. A web app with specific knowledge of the particular user (session cookie, login, etc) may choose to simplify somewhat or make different assumptions.

I am of the opinion that all permission should be user-initiated, by a manual click on the extension icon. But it is certainly possible for the extension to activate the popup upon any connection attempt or request from a page, which would make permission effectively app-initiated - very much like webcam or mic permission currently operates. This wouldn't require any dedicated rpc message type, as the extension is easily able to identify attempted connections from an unknown origin.

**Comment by turbocrime** [comment]
>The majority of crypto wallets accomplish this by using content-scripts to inject something onto the window object. If say window.metamask is present, it knows the user has installed it. If not, it prompts the user to go the the chrome web store.

I believe this is a bad choice, because such a technique provides affirmative confirmation to every page that a wallet extension is present.

Consider the page adversarial until the user manually approves permission.

**Comment by grod220** [comment]
I think there may be a differing vision on what the userflow for authentication is. The industry-wide way it works typically looks like this:

- The extension is not installed
  - The top right hand corner of the screen has a Connect button that when pressed, prompts users to install the extension
- The extension is installed, but the user has not authorized the connection
  - The top right hand corner has a Connect button that when pressed, triggers an approval popup
  - If approved, the Connect button is replaced with the user's account address (or some connected indicator)
- The extension is installed and the user has already authorized
  - Displays user's account address (or some connected indicator)

⬆️ These are the user flows we need to support.

> Web apps may assume the extension is not connected, until an attempted request is acknowledged by the extension

In the normal http world, a fetch would return a `403 Forbidden` response and the UI could display the right thing. However, what is that for our case? At the moment, if we issue a message without an existing recipient, it will "await" forever. Without any support, the best case scenario is for us to put a kind of timeout on the message. This would be kinda unfortunate that the UI would have loading screens everywhere for X seconds. The injected code or exposed txt object allows the web app to know immediately whether it's installed or not.

> Web apps should not be concerned with their own authorization

To support the user flow above, it does need to be concerned about this.

> This 'negative' presence can by default trigger display of instructions

What specifically is a "negative" presence? A timeout?

> When a web app receives responses from the extension

In this case, do you suggest the connect button issue a random grpc query to see if it's connected? Why not just expose a `ping` grpc method or, even better, `isConnected()`?

> I am of the opinion that all permission should be user-initiated, by a manual click on the extension icon

In your vision, do you see the user going to the web app, seeing there is no data, and proactively clicking the extension icon to authenticate? 

> the extension to activate the popup upon a connection attempt

In the industry, it's a bit 50/50 on this behavior. Some web apps do this, but some users (like me) find this annoying. That you land on a page and it throws a popup immediately. Having a `Connect` button tends to be more common and less invasive. Given we are a privacy chain, I think it's best if users themselves trigger authentication events. Otherwise, a bad web app may trigger a popup, get an approval, and doxx that user's addresses because the user just clicked approve on a random popup without context.
