### ISSUE TITLE
No extension = no load

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#292]
When the extension is not installed, the web app shows a blank screen. We should still load the UI, but show the connection button in the top right that directs user to install the extension.

<img width="698" alt="Screenshot 2023-12-11 at 3 52 26 PM" src="https://github.com/penumbra-zone/web/assets/16624263/8c752e75-0195-4e24-b186-4c00aff08421">

**Comment by turbocrime** [comment]
`throwIfExtNotInstalled` is still present and works, but it is called during render and the page tries to create a transport client before rendering anything.

**Comment by grod220** [comment]
That sounds like an issue with the way we create grpc clients. I think we need to change `createChannelTransport` to be lazy loaded and only attempt to open connections when a request is attempted for the first time. Creating a client should be a zero-cost thing.

**Comment by turbocrime** [comment]
more specifically, it is the transport creation that is failing. it used to succeed unconditionally and then surface failures on attempted use, but after much discussion i learned it was desirable to have some immediate indication of connection success or failure before requests were attempted.

in the webapp, the clients are all pre-created and imported from a file where they are created at the top level. last time i looked at this i avoided making creation async, because our es target doesn't allow top-level await, and some of the clients are used in react components where async things are problematic.

some locations in the webapp use dynamic import of the clients, this delays them appropriately. if that's an acceptable solution we could try to generalize that.

**Comment by turbocrime** [comment]
alternatively, could just provide async wrappers something like getViewClient and most of the refactor would still apply. i think that one component is the only sticking point
