### ISSUE TITLE
[Bug] Other wallet extensions block transport between the webapp and extension 

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/web#297]
If the user has other wallet extensions installed (like Leap wallet or Namada) then webapp cannot setup the penumbra extension transport. 
The user just gets a black screen instead of webapp. 
![image](https://github.com/penumbra-zone/web/assets/25391690/076e0692-47e5-400a-bd6f-98d86dc3701f)

**Comment by turbocrime** [comment]
i was able to confirm Leap has this behavior but i was not able to confirm Namada has this behavior. it might have required more configuration to activate the behavior.

they were likely both due to the same error. handler was removing itself, outside the conditional confirming message type and origin. so the handler was removed after any message targeting the window. this is a common init method so we ran into it. fixed in #299
