### ISSUE TITLE
Build output -> Html file based routing

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#310]
At the moment, our web app builds a single `index.html` entry point file. This requires the html server that is serving the site to do something like this: https://github.com/penumbra-zone/web/blob/main/apps/webapp/firebase.json#L6-L11. Wildcard the route so it broadly points to that entrypoint html file. At that point, React routing takes over.

This is problematic as it puts responsibility on the html server where some don't have this ability (aka in our case with pd). An example to test:

```
check out bundle-frontend-into-pd on monorepo
do pd start
go to localhost:8080/index.html
(it doesn't have a / -> /index.html redirect at the moment but this isn't an inherent limitation)
```

We need to change our build output to be html files per route. There are Vite plugins that can help us with these kinds of things. Should investigate:

- https://vitejs.dev/guide/ssr
- vite-plugin-pages
- vite-plugin-ssr/plugin

We also should update our firebase config when we've moved to the new method.

**Comment by turbocrime** [comment]
this involves changing some routes. things like transaction view URIs are formatted like `baseurl/tx/7r4ns4c710n-h4sh` and a static site served without rewriting can't accept that.

such 'parameters' should be applied via the 'anchor' segment of the url, like `baseurl/tx#7r4ns4c710n-h4sh`. this has the benefit of remaining local, the static server will not be aware of the anchor segment.

**Comment by turbocrime** [comment]
alternatively, a hash router could be used for all routes. for the webapp i think this is an okay choice.

**Comment by grod220** [comment]
(from our conversation today @turbocrime @jessepinho)

It looks like we've made some progress on the support of our web app via the penumbra node. With the new hash router: https://github.com/penumbra-zone/web/pull/372, it appears to work. However, hash routing is not idiomatic web routing. It's really a bit of a hack of a tool meant for something else.

Our current Vite build tool leans into the single-page-app philosophy (that is feeling more and more dated). It outputs a single html file and points to the single javascript bundle. We could write code that makes vite supports multiple entry points (multiple html files that points to same bundle). Quite soon after, we'll likely want to use a plugin or write code to do code splitting. And then after, we may want to solve our multiple round trip issue (html -> javascript -> rendering -> more requests). So more custom code for pre-rendering...

We are essentially re-creating our own React "meta-framework". Needs like this are precisely the reason why Remix/Nextjs/Gatsby arose. "create-react-app" cli wasn't enough. The web dev world is moving away from single page apps (and rightly so). Frameworks like Remix (and Nextjs after v13) has taught us how much better server rendering is for dev experience and performance. However, this is not compatible with crypto ethos of less reliance upon servers. We've relegated the responsibility of a web server to only serve static assets.

So what we really need is a meta-framework specifically designed for  server side generated, react static sites. And I think it's [Astro](https://astro.build/). It checks a number of boxes for us:

- File system based routing with multiple entry html entry points by default
- Pre-renders html, doesn't require a roundtrips to download javascript for initial loads
- Javascript bundle code splitting
- Designed for static deployment
- Uses a slick transitions API we could use for animations

Using this would outsource the maintenance of our specific web3 server philosophy.

**Comment by jessepinho** [comment]
One thing I forgot to raise during our convo today, which @turbocrime brought up when we worked on the hash router last week: we still need to support dynamic parameters on our static pages for, e.g., transaction hashes (`/tx/<hash>`). If we switch to HTML file-based routing, we'll need to rework how we get parameters from the URL — either by using a query string, or by using a hash for just the dynamic parameters. In either case, we'll need to ensure that the meta-framework we use supports `pushState` for updating dynamic parameters in the URL, so that we don't have to do a full page reload every time the query string changes. (Or, if we use a hash for the dynamic parameters, our choice of meta-framework will need to support binding React variables to the hash, so that we don't have to reinvent that wheel.)

**Comment by grod220** [comment]
> we still need to support dynamic parameters on our static pages

Query params feel the best for this

>  Astro specifically over Next or another more well-known meta-framework

Indeed Nextjs has SSG via `next export`. But it also feels like Vercel is throwing all their dev effort into server rendering and react server components. They haven't released a SSG feature in years. On the other hand, Astro's static rendering feels more as a first-class citizen to this specific use case. Open to it though!

**Comment by jessepinho** [comment]
OK gotcha — that seems like a fair reason for not using Next.

**Comment by turbocrime** [comment]
i think query parameters are not ok for this: query parameters are transmitted to the host. some things that would be parameters like specific transaction IDs should be considered sensitive information.

as it stands, we don't need the firebase config - should that be removed now?

**Comment by grod220** [comment]
> i think query parameters are not ok for this

In theory, transactions can be viewed by non-owners too. But I see what you mean. Using hashes seem to be just as easy to do in this case.

> we don't need the firebase config - should that be removed now?

Yes, as a part of this task, we should scrap that config and write one that works with normal .html based routing.

**Comment by jessepinho** [comment]
Oof, good catch @turbocrime . @grod220 does this mean we should stick with hash routers after all? or use SSG, but stick sensitive parameters in the hash? (If the latter, this could be messy to implement. I think there's wide support for putting _all_ routing in the hash, but I've never seen a React routing library that uses the hash as a replacement for query params 🤔

**Comment by hdevalence** [comment]
I don't have opinions about the technical specifics but at a product level, the things we're building in this repo would ideally be maximally client-side, so that as much as possible it's "publishing a website" rather than "operating a service".

See https://www.coincenter.org/electronic-cash-decentralized-exchange-and-the-constitution/ for motivation on that front.

**Comment by grod220** [comment]
> does this mean we should stick with hash routers after all? or use SSG, but stick sensitive parameters in the hash?

I'd say the latter. SSG+Hash params. We should be mindful of what qualifies as a sensitive param and make sure it's also passed as a hash. I do not think hitting different routes qualifies as a privacy leak to the static asset server. Overall I'd say the objective is to move away from bespoke routing + vite bundling to something more standard and maintained by the framework itself. So go from this:

```
minifront/
  index.html
  assets/
    bundle.js
```

to this:

```
minifront/
  index.html
  dashboard/
     index.html
     transactions.html
  swap.html
  assets/
    index.js
    dashboard-index.js
    dashboard-transactions.js
    swap.js
```

and our html files going from:

```
<html>
  <body>
    <div id="root"></div>
  </body>
</html>
```

To actual, build-time rendered html that does not require round trips to the server causing waterfall rendering. All of this should be "free" from the framework and not something we should have to configure ourselves. 

And most importantly, should result in the same dist/ output that can be dropped into pd (or really any static file server) and work without special server configuration on re-directing routes.

**Comment by hdevalence** [comment]
> I do not think hitting different routes qualifies as a privacy leak to the static asset server.

Yeah, unfortunately it does, it allows any network adversary to watch a user's activity as they navigate the app (the since the requests are predictable and content-free, they may leak paths through the length of the encrypted data, which TLS does not protect).

In general, we want a minimal frontend structured as a single code payload that the host publishes; the client can then execute that payload, which runs on their device and queries the local view server.

We should use the hashrouter to align with that vision.

**Comment by grod220** [comment]
Oh dear. It's kinda tragic the latest & greatest performance+dev experience in web2 is simply not accessible to us 😢. But I see what you mean. We've basically arrived at the final state with vite CSR, hash routing, & loaders then. Going to open a PR documenting this decision in our docs and why it is like this so later devs don't attempt to "upgrade" this setup.

**Comment by hdevalence** [comment]
Another use case this supports is IPFS-hosted frontends. Having the entire site in a single blob means that we can verify one content-hash and then have everything after that run on the end-user device.

While this might not be ideal in terms of other tradeoffs like you mention, I think it's the right thing to do for minifront — other frontends can make other choices, since the existence of the maximally decentralized minifront option means they won't be chokepoints on users' access to the chain.
