### ISSUE TITLE
start building transactions optimistically while the approval popup is displayed

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#324]
we can hide the latency of proving by starting to build the transaction optimistically while the user is looking at the approval popup. if we get the proving fast enough (faster than the time to review the tx plan) we may be able to have "apparently instant" building.

https://twitter.com/hdevalence/status/1738713884138336306

**Comment by turbocrime** [comment]
currently, the building toast blocking time includes broadcast and confirmation

**Comment by TalDerei** [comment]
References #113

**Comment by hdevalence** [comment]
> currently, the building toast blocking time includes broadcast and confirmation

there's not a way to change this with the current view service rpc, right? should we change it so that it does streaming responses, for the different stages (returning a message when built, broadcasted, confirmed, etc)?

**Comment by grod220** [comment]
> there's not a way to change this with the current view service rpc, right?

We now can use the `AuthorizeAndBuild` method which would achieve the original intention of this issue.

> should we change it so that it does streaming responses, for the different stages

I think this would be good regardless. At the moment, we have a generic loading spinner on the web app. It doesn't give a ton of information to the user on what actually is happening (or what stage something actually errored).

**Comment by turbocrime** [comment]
after reading this issue the other day i did some work to split the broadcast time to a separate toast, i'll make a PR. i thought about streaming responses back from offscreen while we worked on that and i think that is simply achievable too, but i didnt bring it up in the interest of limiting scope.

build progress would require a spec change if we want to inform the client, but maybe it makes sense to display transaction build progress in the extension icon or popup, which would require no spec change.

it seems like some build steps require authorization data? is that correct? if we want to optimistically build while pending interactive approval, we could just provide the auth, and make broadcast the approval-gated step. that would require no spec change, but that seems unsafe since auth data flows all the way back to the app.

with #282 , we possibly could keep auth in-extension at all times, and use context or an 'interceptor' to inject authorizationData for approved requests.

**Comment by hdevalence** [comment]
We can and should change the view rpc definitions to allow giving progress info. However, we can't easily do it at the moment because I made a large set of consensus breaking proto changes (hopefully the last set before mainnet) and so the current protos aren't compatible with the current testnet. (We've had this problem before but shouldn't have it again past the 15th of January).
