### ISSUE TITLE
Update code to support v0.65.0

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#338]
Believe Jan 16th target date for new testnet launch. After launch do:

- Update bufbuild & wasm crate npm deps. Usually easiest to do `pnpm up -r --latest`. However, we have that vitest dep issue: https://github.com/penumbra-zone/web/issues/271 that we should avoid for this ticket.
- Fix breaking changes. There are a few new view services changes.
- Update Manifest version (probably should be v3.2.0): https://github.com/penumbra-zone/web/blob/5c8c369dbdad31e0258b375fd090429d011d05aa/apps/extension/public/manifest.json#L4
- Merge
- Make new release on this repo (same as manifest version)
- New tag+release triggers approval for chrome extension submission.

**Comment by hdevalence** [comment]
It might be good to start making changes to support 0.65 in advance, in order to enable building key features like an approval dialog (which needs the new tx plan definitions). Going forward we won't be making breaking proto changes so this won't be a recurring issue, but in this case we could consider changing the extension/frontend to target preview a week in advance or so.

Maybe we flip a switch to aim the deployment at app.testnet-preview.penumbra.zone and don't publish an extension update?

**Comment by grod220** [comment]
Meeting discussion: Can start earlier and cause week of breaking changes in order to get ahead on this
