### ISSUE TITLE
Retry logic for stale extension state

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#339]
Relates to: https://github.com/penumbra-zone/web/issues/51

It's a bit hard to replicate, but when a request hasn't come to the extension in a while it's common to get a `Receiving end does not exist` error. Upon refreshing the page it fixes itself. I believe the issue relates to the extension wake up time. In the previous content scripts, we used [exponential backoff](https://www.npmjs.com/package/exponential-backoff) to simply retry. This resolves the issue.

<img width="805" alt="Screenshot 2024-01-03 at 9 04 48 AM" src="https://github.com/penumbra-zone/web/assets/16624263/3971d26f-7dbf-40a7-815f-79eae732b935">

**Comment by turbocrime** [comment]
notably connectrpc code.unavailable is used to suggest backoff to the client and could be used to trigger this behavior

i transport may need some way to distinguish between 'extension killed by chrome runtime' and 'extension chooses to ignore connection'

there is a connectrpc service abort feature that may be useful here

**Comment by jessepinho** [comment]
[This SO answer](https://stackoverflow.com/a/57610828/974981) has a couple tips that _may_ be relevant:
1. Use `chrome.runtime.onMessageExternal.addListener` instead of `chrome.runtime.onMessage.addListener`
2. Add `externally_connectable` config to the manifest.

That said, this is super hard to debug since it appears that the only way to trigger this bug is to just... wait. Not sure what the timeout is before this error happens, but it seems to be on the order of an hour or so. I'm honestly not sure how to proceed until I know how to consistently reproduce this error, and more quickly.

**Comment by grod220** [comment]
It's hard to know the exact nature of why this happens. I think it may be that our request is faster than the time it takes for our service worker to wake up and handle it.

In the past, we had a simple request retry when an error was thrown. However, in our updated messaging stack, it's not super clear on what part of our system would do this retry. This error cannot seem to be easily caught and gets thrown from a mysterious part of the system.

**Comment by turbocrime** [comment]
errors have been significantly refactored but 

<img width="476" alt="Screenshot 2024-03-14 at 13 48 13" src="https://github.com/penumbra-zone/web/assets/134443988/8d04a2ae-16ef-4309-98cf-30022177b085">

it should now be possible for the page to identify a failed transport by detecting this failure with an errorboundary. the only remedy is to reload the page

**Comment by jessepinho** [comment]
@turbocrime I'll account for this in #752
