### ISSUE TITLE
Blocks are not persisted to indexed-db transactionally, leading to possibly unspendable funds, state divergence

### ISSUE THREAD

**Issue by plaidfinch** [penumbra-zone/web#34]
It is extremely important for the correctness of synchronization that each compact block's state changes are stored _all at once_ or _not at all_. Otherwise, an interruption to synchronization could lead to a state where only some of the state updates contained in a compact block have been written to storage. This is critical to get right: getting it wrong can lead to (temporarily) unspendable funds, in a variety of different ways (missing notes mean balance can't be updated, missing transaction data means past transactions can't be inspected, missing swaps mean swaps can't be claimed, missing state commitment tree updates mean notes can't be spent, and then further updates will cause its root to diverge, making all funds unspendable). As noted, these state corruption issues do not render funds _permanently_ unspendable, but the distinction between state corruption and permanent loss of funds (especially in the absence of comprehensive user-friendly error handling) will be entirely opaque to most users. This scenario will appear to most users as if something has gone permanently, seriously wrong.

Currently, writes to storage happen all over the place, in a variety of different functions, meaning sync interruption has a strong chance of introducing state inconsistencies within a single block. In addition to the possibility of torn writes within a single block, the current code only persists the changes to the SCT every 1000 blocks, which means that there is a 99.9% chance that an interrupted synchronization run will lead to corrupted database state (and a divergent SCT root). The TCT is designed to be serialized incrementally, so that this kind of periodic checkpointing is unnecessary. Its updates can and must be serialized every single block, along with all the other state changes, every block.

In the code as it stands, the SCT divergence that would result from interrupted sync appears to be patched over by code that wipes the storage and restarts synchronization if it detects an SCT root divergence: this hack should not be necessary, because the SCT should never diverge. If the SCT ever diverges, this should be viewed as a _programmer error_: it should not be patched around; it should be reported as a critical bug, and triaged so that it never happens.

To resolve these issues, we should refactor the block synchronization code to make a single transactional write to the database for each and every block, [just as the native Rust view code does](https://github.com/penumbra-zone/penumbra/blob/main/crates/view/src/storage.rs#L1198-L1453). This can be done by making use of the [`IDBTransaction`](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction) type, which allows a series of reads and writes to be done transactionally on the database, analogously to the way we do it in the native Rust view code.

One important thing to note about this change: it is also critical that any in-memory representations of stored data are only updated in the in-memory view server _exactly if and only if_ the corresponding writes to their stored representations are also updated successfully. In particular, the native Rust view server takes special care to ensure that the SCT is _not_ updated in memory until _after_ the database transaction is successfully committed. It is easy to do this because the SCT is a copy-on-write data structure: it is efficient to make a `.clone()` of it, make changes to that copy, and then finally (only after the transaction is committed!) set the view server's SCT field to that modified copy. This ensures that the view server's version of the SCT always matches what is on disk, even in the event of an error during synchronization.

**Comment by Valentine1898** [comment]
> current code only persists the changes to the SCT every 1000 blocks, which means that there is a 99.9% chance that an interrupted synchronization run will lead to corrupted database state (and a divergent SCT root)

That's not entirely true 
We write SCT data to indexedDb, and only after a successful write do we update the last_saved_block value. 
This means that if we suddenly stop synchronization at block 1579, it means that the value of `last_saved_block` will be 1000 and it will correspond to the state of the 1000th SCT block in indexedDb. 
We will be able to successfully resume synchronization from the 1000th block. 
We save the SCT state every 1000 blocks because if we do this every block, synchronization will be much slower.

**Comment by Valentine1898** [comment]
I agree that we need to transactionally save SCT and last_saved_block data (in the old version of extension last_saved_block was not saved in indexedDb at all, but in extension storage)

At the same time, I suggest to consider as a speed optimization mechanism our idea of saving SCT and last_saved_block state in indexedDB not every block, but once in 100, 1000 or 10000 blocks. 
At the same time, save notes, swaps, nullifiers every block. 
Yes, this will cause some notes, swaps to be written 2 or more times in indexedDB, but it will not cause duplication since they have a unique identifier.

**Comment by Valentine1898** [comment]
The basic idea is that our notes, swaps, nullifiers don't occur every block, they occur rarely. Keeping them does not critically affect the synchronization speed. 
At the same time, the SCT state changes every block, regardless of whether our transactions were there or not. This leads to the fact that every block we need to ensure that all SCT changes are saved in indexedDb

**Comment by Valentine1898** [comment]
It looks something like this
#height
#1000 - get SCT updates -> update SCT indexedDB state and update last_saved_block
...
#1021 - found new note and tx -> save note, save tx 
...
#1871 - found new swap and tx -> save swap, save tx
...
#2000 - get SCT updates -> update SCT indexedDB state and update last_saved_block

Any interruption of synchronization causes us to resume synchronization with `last_saved_block` and with the SCT state that corresponds to `last_saved_block`. In this case, if we for example interrupt synchronization at block 1999, it means that when resuming from block 1000 we will already have notes, swaps and txs from blocks #1021 and #1871 in indexedDB. But taking into account the fact that 
- we can't use a wallet that is in the process of synchronization 
- re-saving does not lead to synchronization failure and does not create duplicates. 
So it seems that we improve the synchronization speed without having negative consequences from it

**Comment by grod220** [comment]
If saving new notes/swaps as we scan effectively make them unusable without the SCT update, I'm not sure why we'd do them at all without also the SCT alongside.

It seems like we should be doing all updates at once or not at all. Also, we should move to make these updates in a single transaction so they are atomic. At the moment, they are individual database writes.

Whether that is every block or every nth block, is something we should manually test to see how expensive these db writes are. For pcli, it appears they are doing the db writes on every block and it doesn't hurt the performance.

**Comment by grod220** [comment]
Fixed on last PR merge 👍

**Comment by TalDerei** [comment]
@grod220 from my perspective, processing blocks in the block processor isn't _actually_ atomic, which makes local state corruption far more likely, right?

**Comment by grod220** [comment]
The BlockProcessor is quite complex. Since this ticket, we've added a great deal to it, but have not maintained the atomic nature of the saves to the db. Think they fall into three categories. I don't see any obvious bugs created by category #2, but regardless, it is likely still worthwhile to create a new API for the storage interface that stages the db saves and right before the end of the loop, calls a function to commit them all at once.

**1 - Currently atomically saved together per-block:**
- SCT updates
- New notes
- New swaps
- Sync block height

**2 - Currently independently saved within block (if sync is interrupted, will still be persisted):**
- App params
- FMD params
- Gas prices
- New asset metadata found
- Updating height spent of spent notes/swaps
- Auction statuses
- New transactions
- Asset prices
- Next epoch height

**3 - Currently independently saved over many blocks:**
- Validator info table. Triggers an update at new epochs. Will independently stream the latest validator list + prices of delegation tokens and save them. This is a quite long process, so does not block block-processing from continuing.

**Comment by TalDerei** [comment]
> create a new API for the storage interface that stages the db saves and right before the end of the loop, calls a function to commit them all at once.

filed https://github.com/penumbra-zone/web/issues/1726
