### ISSUE TITLE
Import Asset Registry from `Cosmos Asset List`

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#428]
The extension needs a way to import its own DenomMetadata definitions that refine those defined on-chain. In particular, the on-chain definitions won't have any denom units or other information about IBC assets. The extension needs to be able to import those from the [Cosmos Asset List](https://github.com/cosmos/chain-registry/tree/master#assetlists). This is a somewhat security-critical step, because it's how we present to users information about which assets are "real" and which are random other channels. This is also an opportunity, since we can, e.g., show source chain info in the icon or ticker.

See: https://github.com/penumbra-zone/web/issues/392 for discussion on this

**Comment by hdevalence** [comment]
I'm not sure we need to import the entire cosmos asset list to start. None of those assets will correspond directly to assets on Penumbra, to start, since we'll have to define IBC mappings for all of them.

I think a good first go at this would be to:

- [ ] in JSON files, define "refined" `DenomMetadata` for assets on the testnet chain (we already have some JSON sitting around, from what I've seen in other PRs, it could move out into configuration files)
- [ ] when initializing the view server database, add a step that reads the configuration data and registers the contents as known assets

Then when syncing, when the view server sees an asset for the "first time", it will already have been registered with the configuration data's `DenomMetadata`.

The configuration data should be "refined" in that it should have fields filled in that aren't present in the on-chain metadata. For instance, the on-chain data never includes the "symbol", but the extension should be rendering assets via symbol, so the extension should be specifying `DenomMetadata` with the symbol set.

**Comment by hdevalence** [comment]
As of https://github.com/penumbra-zone/penumbra/pull/3702, this exists in the protos, and at least the Rust implementation of `DenomMetadata` can parse the JSON from the cosmos asset list without problems. I would expect the same thing is true for the Buf generated code, though it might be necessary to configure the deserialization to ignore unknown fields.
