### ISSUE TITLE
Implement pricing

### ISSUE THREAD

**Issue by grod220** [penumbra-zone/web#446]
Currently, our UI has a number of $usdc pricing placeholders. We should come up with a way to get actual data here. In most crypto protocols, pricing is usually provided via querying an on-chain oracle (like Pyth) or a node with a simulate-swap endpoint. However, for a privacy dex, we likely have to be more intentional about this.

In core, we have a [simulate swap request](https://github.com/penumbra-zone/penumbra/blob/66b13e98643b8af8285238c62657ded81e8824f1/proto/penumbra/penumbra/core/component/dex/v1alpha1/dex.proto#L545-L563), but calling this for each user's asset would expose their wallet holdings.

Ideas:
1. Simulate swaps for all assets to usdc in registry in web app. This would create a kind of global table and obfuscate the user's exact holdings.
2. ~~Put pricing data in compact block.~~ Use the pricing data already in the compact block. View server can use something like `BatchSwapOutputData` in the compact blocks to compute an average price, and if there aren't enough trades it computes "no price available". It then would be saved to db and exposed via `DenomMetadata` or another rpc pricing endpoint.

Reference: [initial discord conversation](https://discord.com/channels/824484045370818580/1044457038886998137/1200141419273265383)

**Comment by grod220** [comment]
@hdevalence fyi

**Comment by hdevalence** [comment]
Edited (2) to clarify that the pricing data is already in the compact block. We just need to define a rule that determines how much volume has to have happened and how recently, to determine that the price is "real".

**Comment by hdevalence** [comment]
Branching off from this, I'm actually wondering if we should rethink pricing to be a little bit more general. We have a situation where we'll have a bunch of assets that have known relations to another asset. For instance, a validator's delegation token has an equivalent value in the staking token. We'll probably want to be able to display this. Or, an LPNFT has certain reserves, etc. Can we provide this information to a frontend in the same way we'd provide information about an equivalent USD value, rather than baking in the assumption that we only care about a single anointed token as the numeraire?

**Comment by grod220** [comment]
Wouldn't the fact that each token requires different pricing methods be an indication we _can't_ generalize this? If the frontend would be responsible for pricing it would have to do something like:

- **For normal tokens**: create pricing table for each asset (querying node for simulated swaps) and use table locally
- **For LP NFTs**: estimate withdraw (get range, get underlying assets for pool, do some math... can this be queried?) and combine prices of assets from above
- **For delegation token**: map to staking token, price token

or should this logic be in the extension with the metadata proto just having an `estimatedPrice: <native>` field?

**Comment by hdevalence** [comment]
Right, what I'm saying is that it shouldn't be the frontend's responsibility to figure out what the pricing is, ideally we would figure out how to handle all the use cases we care about by augmenting the `ValueView` with additional fields. Taking your three use cases:

- **Ordinary Tokens**: the extension can estimate prices in any numeraire (or "no price known") using the information already in the compact block (the `BatchSwapOutputData` has a feed of trades, we can pick heuristics about how much volume and how recent it should be in order to consider it an "available" price);
- **LP NFTs**: there's no math necessary here, only a specific query to the fullnode for the current reserves (a _pair_ of assets), and the extension's price indexes can convert those into an Option of the numeraire);
- **Delegation Tokens**: useful to display the amount of staking token (requires either a specific query or ~daily polling of the RPC to get all validator rates) and also the value in the numeraire.

Two observations here:

1. We have use cases for having more than one "equivalent value", as particularly demonstrated by the delegation token case.
2. We have use cases for having the equivalent value be a _basket_ of assets rather than just one asset, as particularly demonstrated by the LPNFT case.

**Comment by grod220** [comment]
Replaced by: https://github.com/penumbra-zone/web/issues/530
