### ISSUE TITLE
Filter out LpNft's from swap asset selector

### ISSUE THREAD

**Issue by jessepinho** [penumbra-zone/web#485]
When selecting an asset to swap, we see LpNfts included:
![](https://private-user-images.githubusercontent.com/1121544/303194333-67fc134e-7ebf-48ad-85e6-2b0a94ed2e96.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0Mjg2NjEsIm5iZiI6MTcwNzQyODM2MSwicGF0aCI6Ii8xMTIxNTQ0LzMwMzE5NDMzMy02N2ZjMTM0ZS03ZWJmLTQ4YWQtODVlNi0yYjBhOTRlZDJlOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDhUMjEzOTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU4ODc5NDUzZDhiOTJlNGFlMjU2MGY3MzhhN2Y1NmJkY2IyYWZhZDAwMDJkZGVlODRiZGRlZTdmZDE4MmFlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wdtlMnS1VeQeVJrbS2gn6vR5yEvGFCF3DFuxdsgXT44)

Per @grod220 's [comment](https://github.com/penumbra-zone/web/pull/476#pullrequestreview-1870071861):

> We should not have lpnft's in that selector drop down box at all.

This ticket is to filter for only spendable assets wherever we have asset selectors. We'll likely want to use [the `assetPatterns` const](https://github.com/penumbra-zone/web/blob/5f5e98bf6e85dc58f19df83977f6aee748a6ca87/packages/constants/assets/index.ts).

**Comment by jessepinho** [comment]
@grod220 we'll want to filter out any assets that match _any_ of those patterns, right? (Not just `lpNft`s?)

**Comment by hdevalence** [comment]
I'm a little confused by the "spendable assets" terminology. These are all assets and they're all spendable by the user -- the LP NFT, for instance, is "just another token", spendable like any other. So while we might not want to show them in a swap selection in the UI, this is just a UI decision, not anything about the token.

Looking at the list of patterns there, we definitely want to be able to swap delegation tokens. The LPNFTs are probably the only ones we don't want to support.

As an aside, we should think about how we want to render these tokens. The delegation tokens are probably a good starter case since they'll be needed for staking handling.

**Comment by jessepinho** [comment]
Ah — thanks for filling in the gaps in my knowledge, @hdevalence. @grod220 , would you mind adding some clarification to this issue description about exactly what should show up in that box, then?

**Comment by grod220** [comment]
For LP tokens, it's simple enough to just filter those out of the selection box using that regex helper.

For delegation tokens, do we anticipate there being pools for these? Will this allow folks to essentially offer a discount on the token in exchange for getting around the unbonding period?
