### ISSUE TITLE
Avoid streaming entire IDB tables

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#486]
After #312 and #481 we are now iterating over streamed queries, instead of loading the entire query into memory

This is an improvement but could still get better. Inspecting and filtering items in the table should, as much as possible, be done by the database, not the caller. IDB can handle more specific queries, if we prepare index by an object's attribute.

For example, in transaction-info.ts, https://github.com/penumbra-zone/web/blob/f866ef4de9eb1f51ccc6a518d9806be0046549df/packages/router/src/grpc/view-protocol-server/transaction-info.ts#L8-L14

Which is backed by our idb query helper iterateTransactionInfo,

https://github.com/penumbra-zone/web/blob/8e13b82921c4f97c6972c04b478b18bc52ee40ed/packages/storage/src/indexed-db/index.ts#L187-L198

We could instead [query a key range](https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/bound_static), if we prepared the schema to index transactions by height, the way we index swaps, notes, &c by index

https://github.com/penumbra-zone/web/blob/f866ef4de9eb1f51ccc6a518d9806be0046549df/packages/storage/src/indexed-db/index.ts#L74

would become

```ts
        db.createObjectStore('TRANSACTION_INFO', { keyPath: 'id.inner' }).createIndex('height', 'height');
```

with schema

```ts
  TRANSACTION_INFO: {
    key: Jsonified<Required<TransactionInfo>['id']['inner']>; // base64
    value: Jsonified<TransactionInfo>;
    indexes: {
      height: Jsonified<Required<TransactionInfo>['height']>;
    };
  };
```

and expose the index appropriately through our queriers

```ts
  async *iterateTransactionInfo(lower: bigint, upper: bigint) {
    const dbTx = this.db.transaction('TRANSACTION_INFO');
    const dbIdx = dbTx.store.index('height');
    for await (const { value } of dbIdx.iterate(IDBKeyRange.bound(lower, upper)))
      yield TransactionInfo.fromJson(value);
  }
```

which would greatly simplify transaction-info.ts

```ts
import type { Impl } from '.';
import { servicesCtx } from '../../ctx';

export const transactionInfo: Impl['transactionInfo'] = async function* (req, ctx) {
  const services = ctx.values.get(servicesCtx);
  const { indexedDb } = await services.getWalletServices();

  yield* indexedDb.iterateTransactionInfo(req.startHeight, req.endHeight);
};
```

this technique could be applied generally through most of our full-table idb methods.

some situations involving compound indicies can be handled, but idb does not have good support for complex compound indicies. things like assets.ts with multiple fields

https://github.com/penumbra-zone/web/blob/f866ef4de9eb1f51ccc6a518d9806be0046549df/packages/router/src/grpc/view-protocol-server/assets.ts#L19-L52

would not be easy to provide indexes for. you can see more detail on this subject

*  https://yathit.github.io/ydn-db/doc/query/cmpidx.html which is documentation for another library, but it does provide insight into the limitations of idb compound queries
* https://stackoverflow.com/questions/12084177/in-indexeddb-is-there-a-way-to-make-a-sorted-compound-query a stackoverflow answer that is thorough but more complex to understand

**Comment by grod220** [comment]
Yep, this makes sense. @Valentine1898 perhaps you can pick this up when you're next available? Thinking you may be a good candidate for this as it may impact the testing tracking issue you are working on? https://github.com/penumbra-zone/web/issues/333

**Comment by Valentine1898** [comment]
Yeah, sure, I'll start that today

**Comment by Valentine1898** [comment]
We have only a few streaming queries at the moment 

1. `iterateSpendableNotes`
Allows filtering by several fields: `assetId`, `addressIndex`, `includeSpent`, `amountToSpend`
It is impossible to add an index for `amountToSpend`, because it is analogous to the SQL function `SUM BY`. 
And for `assetId`, `addressIndex`, `includeSpent` we need a compound index, which is poorly supported in indexed-db. Also, we should take into account that all filtering fields may not be defined, rpc specification allows it. 

2. `iterateTransactionInfo`
In iterateTransactionInfo there are only 2 filtering parameters `startHeight` and `endHeight`, and both parameters are about one field in indexed-db. But, both parameters are optional
This means that we can have 4 cases
- `startHeight` and `endHeight` are not defined and we should not iterate over the index. 
- Only `startHeight` is defined and we should only do `IDBKeyRange.bound(lower)`
- only `endHeight` is defined and we should only do `IDBKeyRange.bound(upper)`
- both defined and `IDBKeyRange.bound(lower, upper)`

3. `iterateAssetsMetadata`
Difficult filtering conditions with patern search, not sure if index implementation is possible 

4. `iterateSwaps`
No filtering

Based on this, only `iterateTransactionInfo` is a potential candidate for adding an index, and using iteration on the index. But taking into account that filtering parameters are optional, it seems that we will get code complication and testing, instead of minor query optimization. 
My suggestion is to leave everything as it is.

**Comment by grod220** [comment]
@Valentine1898 think we can close this issue?

**Comment by Valentine1898** [comment]
> @Valentine1898 think we can close this issue?

Missed the comment, I think yes
