### ISSUE TITLE
Fix regressions in JSON view

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/web#836]
The JSON in the transaction view page now has noticeable regressions:

- the view is not collapsible or hidden by default
- the fields are not copyable
- larger objects cannot be collapsed and restored on demand: clicking the ellipsis expands arbitrarily large content, with no way to collapse it.

We should restore the functionality that previously existed, I'm not sure why this needed to be rewritten.

**Comment by grod220** [comment]
Context:

- We start getting `unmet peer dependencies` warnings in our console when we do `pnpm install`.
- Turns out react's most used json viewer (`react-json-view`) is now abandoned by its maintainer. 
- Given the required peer dependency is an old version of react, we are in a bit of a risky state by keeping this dep. A new version of react we update to could silently break our tx details page. We are kinda just lucky it hasn't so far.
- Time to look for a new package to replace it
- `@textea/json-viewer` appears to be actively maintained and feels like a kind of successor given how similar the features/design looks. A PR (https://github.com/penumbra-zone/web/pull/696) is opened to migrate to this. Has feature parity. After review, it's brought up that this would increase our bundle size and that we should seek for something more lean. `react-json-view-lite` is then used instead given how lean it is. However, we lose the features you mentioned above.
- Given how minimal it is, a later PR (https://github.com/penumbra-zone/web/pull/813) adds more features like design improvements and open/collapse logic.

To recover those features from the migration, we could simply revert to the commit in that PR that implements `@textea/json-viewer`. It is a larger size than `react-json-view-lite`, but perhaps it doesn't matter. Minifront's bundle size comparisons with different json viewer libs:

- `react-json-view` (original): 4.50 MB
- `@textea/json-viewer`: 4.49 MB
- `react-json-view-lite`: 4.40 MB

The 92kb diff feels like something we can live with.

**Comment by turbocrime** [comment]
i think i made some opinionated choices in #813 that conflict with @hdevalence's preferences

1. i deliberately made the root view expanded by default and hide its collapse button, but that doesn't have to be the case
2. i deliberately made all fields below the 'collapse level' default to expanded, so that inspecting a deeply-nested field didn't require may clicks
3. large objects are indeed collapsible on demand. but notably the collapse is achieved with the arrow next to the field name, and not the ellipsis which disappears when expanded. a changing collapse/expand arrow button is supported, but i chose to hide the 'expand arrow' in favor of the ellipsis alone, as an aesthetic choice
4. text fields no longer each pesent an individual copy button, but a single click highlights the entire field (even the part after the ellipsis) and it is copyable
5. buttons for 'expand/collapse all' and 'copy all' are available in the top right

i advocated react-json-viewer-lite as a replacement for the unmaintained dep in the interest of bundle size, and i think bundle size should be the primary concern when we select dependencies, but i have no particular attachment otherwise

**Comment by turbocrime** [comment]
notably, react-json-view-lite developer AnyRoad seems [very responsive to issues](https://github.com/AnyRoad/react-json-view-lite/issues/22) so we may be able to just ask or PR for things like copy button

**Comment by hdevalence** [comment]
Thanks for the context, I didn't realize that there wasn't just a concern about the presence of a maintainer but also that it was actively at risk of breakage.

In general, I think:

- for a package like this, it's probably fine for the dependency to be "unmaintained" if there's not an active problem with it and it's not core functionality
- bundle size should probably not be a concern

Fine-tuning the JSON formatting seems like a pretty low priority relative to our other work so I'm happy to close it out.
