### ISSUE TITLE
sync exponential backoff accumulates regardless of how far apart failures are

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#871]
the 'attempt' count should reset to 0 if sync is progressing

**Comment by jessepinho** [comment]
Hm, not sure I understand this.

Is this the issue?
1. The block processor starts syncing.
2. `syncAndStore` throws at some point during the syncing process (which is a long-lived process, since it calls `compactBlockRange` with `keepAlive: true`).
3. `backOff` considers that a failure, and thus increases the time it waits until calling `syncAndStore` again.
4. Steps 2-3 repeat several times due to intermittent failures with the RPC node for some reason.
5. Even though the failures are intermittent, the backoff time is now potentially huge. The next time `syncAndStore` throws, `backOff` waits a very long time to start syncing again.

Is that correct?

It's a tricky problem, since technically `backOff` is working as designed in this case 🤔 

It seems that we're using `backOff` for two reasons here:
1. to avoid spamming the RPC node if we can't initially connect.
2. to automatically retry when `syncAndStore` fails — even if the "failure" is quite a bit later.

Please confirm if my understanding of this problem is correct. If so, perhaps we can split out reasons 1 and 2, and only use `backOff` for reason 1.

**Comment by turbocrime** [comment]
this concept is correct. the issue is distinguishing the two cases

**Comment by turbocrime** [comment]
prax issue. i believe this is completed
