### ISSUE TITLE
remove storage access from `HandlerContext`

### ISSUE THREAD

**Issue by turbocrime** [penumbra-zone/web#923]
~~this data should be provided at rpc init~~

edit to clarify: this data should be provided in `HandlerContext`, which is created in `service-worker.ts` in order to start up rpc services.

any 'wallet' attribute access should be abstracted into context key access retrieving the desired data.

- [ ] https://github.com/penumbra-zone/web/blob/ed38353a302995447a975120123ab917f70a1315/packages/router/src/grpc/custody/authorize/index.ts#L28
- [ ] https://github.com/penumbra-zone/web/blob/ed38353a302995447a975120123ab917f70a1315/packages/router/src/grpc/view-protocol-server/wallet-id.ts#L10
- [x] https://github.com/penumbra-zone/web/blob/ed38353a302995447a975120123ab917f70a1315/packages/router/src/grpc/custody/authorize/index.ts#L25

**Comment by Valentine1898** [comment]
What do you mean by "rpc init"? It seems that right now we don't have an initialization function for rpc to which we can pass this data. 

Also, the rpc probably shouldn't know anything about the encryption method of the seed phrase, third parties will probably want to choose a different storage and encryption method. 
So instead of passing `wallets` and `passwordKey` separately, we should consider passing `spendKey`.

**Comment by turbocrime** [comment]
rpc init is not a specific method or function but refers to everything that happens in service-worker.ts to stand up rpc services.

yes, we should provide either `spendKey` as a context item or derive it from the `fullViewingKey` already in context.

**Comment by Valentine1898** [comment]
> yes, we should provide either spendKey as a context item or derive it from the fullViewingKey already in context.
`spendKey` cannot be derived from `fullViewingKey`

**Comment by turbocrime** [comment]
fixed in #1274
