### ISSUE TITLE
Client-side mechanism for continuous GDA

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/web#981]
GDA pricing mechanism:

10m: 4 auctions, 60 blocks long (5m), step_count=60, start heights ~ poisson(lambda = 0.775/min), rel gas = 480x
30m: 12 auctions, 60 blocks long (5m), step_count=60, start heights ~ poisson(lambda = 0.607/min), rel gas = 1440x
1h: 12 auctions, 120 blocks long (10m), step_count=60, start heights ~ poisson(lambda = 0.303/min), rel gas = 1440x
2h: 24 auctions, 120 blocks long (10m), step_count=60, start heights ~ poisson(lambda = 0.272/min), rel gas = 2880x
6h: 36 auctions, 240 blocks long (20m), step_count=60, start heights ~ poisson(lambda = 0.129/min), rel gas = 4320x
12h: 36 auctions, 480 blocks long (40m), step_count=60, start heights ~ poisson(lambda = 0.064/min), rel gas = 4320x
24h: 48 auctions, 720 blocks long (1h), step_count=60, start heights ~ poisson(lambda = 0.042/min), rel gas = 5760x
48h: 48 auctions, 1440 blocks long (2h), step_count=60, start heights ~ poisson(lambda = 0.021/min), rel gas = 5760x

Source: [Discord](https://discord.com/channels/824484045370818580/938328380917559326/1235723630965686363)
pcli reference: https://github.com/penumbra-zone/penumbra/pull/4362

**Comment by jessepinho** [comment]
@TalDerei could you please add some detail here? Not sure what this ticket refers to — isn't the pricing mechanism in core, not the frontend?

**Comment by erwanor** [comment]
Minifront needs to do parameter selection about duration and price windows and that translates into scheduling a collection of auctions with specific parameters. I have a sketch of how this work but we need to do more pairing to turn this into a prototype over the next few days.

**Comment by erwanor** [comment]
Here's a made up example of a dumb GDA mechanism with a constant price curve and for some reason we want to execute at every block over the next six hours.

`duration_second = 6h = 6*60min = 6*60*60s = 21600s`
`num_blocks = duration_second / 5 = 4k`
`num_step = num_blocks`

But since the maximum step count for a single auction is 255, this doesn't work, we need to have a way to schedule back-to-back auctions for each chunk. We should meet and jam about this, I think it will be very clear with a visualization

**Comment by jessepinho** [comment]
Ah, that seems related to [this comment](https://github.com/penumbra-zone/web/pull/967#discussion_r1585777241).

Let's discuss tomorrow!
